# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2013-2018
  project: slub_events
  version: 2.2
  release: 2.2.2
  html_theme_options:
    github_repository: slub/slub_events
    github_branch: master
  latex_documents:
  - - Index
    - slub_events.tex
    - SLUB Event Management
    - Alexander Bigga
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
